### ISSUE TITLE
PhotosMasonry Component

### ISSUE THREAD

**Issue by TrixieL** [xuopled/ced.photo#1]
Hi Cedric, 

Thank you very much for your reply. However, I was wondering about the basic usage of the PhotosMasonry Component. I have used the ImageLightbox component as well. So basically I have something like this:

`...
import PhotosMasonry from './PhotosMasonry.jsx';
...
const photos = [
    "https://unsplash.it/400/500?image=955",
    "https://unsplash.it/200/300?image=916",
    "https://unsplash.it/300/300?image=110",
    "https://unsplash.it/300/300?image=206",
]
class 
   render() {
       return (
            <section className="masonry" id="masonrySection">
                <PhotosMasonry photos={photos} />
           </section>
      );
   }
`
But it won't appear and having an 'undefined' error :(

**Comment by TrixieL** [comment]
I have managed to fix it :)
Now I am wondering if there is anyway to show certain number of pictures considering the resolutions. For example:
https://cl.ly/253U1g30271A

Thanks!

**Comment by TrixieL** [comment]
I have managed to fix it :)
Now I am wondering if there is anyway to show certain number of pictures considering the resolutions. For example:
https://cl.ly/253U1g30271A

Thanks!

**Comment by cedricdelpoux** [comment]
Could you please open an issue on https://github.com/xuopled/react-responsive-masonry/issues ?

Thank you very much. I close this issue because it is just a website using react-responsive-masonry
